//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Hospitales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento_Medicamento
    {
        public int IdTratamiento { get; set; }
        public int IdMedicamento { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
